### PR TITLE
Add Dockerfile for bintray-package and `assets/*`

### PR DESCRIPTION
**Pull request by SimonXming**
* Add Dockerfile.package
* Add `assets/*`

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@SimonXming Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/rabbitmq?repositoryId=rabbitmq/concourse-bintray-resources&pullRequestId=2)!

[Click here](https://cla.pivotal.io/sync/rabbitmq?repositoryId=rabbitmq/concourse-bintray-resources&pullRequestId=2) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@SimonXming Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/rabbitmq?repositoryId=rabbitmq/concourse-bintray-resources&pullRequestId=2)!

**Comment by michaelklishin** [comment]
@dumbbell OK with you to merge?

**Comment by dumbbell** [comment]
I don't know Docker so I can't comment on this change. As long as the resource still works, that's fine with me :-)

**Comment by SimonXming** [comment]
> I don't know Docker so I can't comment on this change. As long as the resource still works, that's fine with me :-)

I didn't modify the source code, just add Dockerfile to build the image. AFAIK, concourse required resource type existing as docker image to be used in the pipeline. This is also the way we are currently using bintray-resource. Anyway, I think the resource should be still works. :)

**Comment by hairyhum** [comment]
LGTM. In our pipelines we build executables and docker image as two separate steps, and then publish the image to https://hub.docker.com/u/pivotalrabbitmq 
Still, it won't hurt having all the build scripts here, if it works.

**Comment by michaelklishin** [comment]
Let's give this a try.

**Comment by gerhard** [comment]
This is decent, thank you @SimonXming.

What are your thoughts on using [clux/muslrust](https://github.com/clux/muslrust) to build a static binary which is then added into a [scratch](https://hub.docker.com/_/scratch)-based image?

For more context on the above, [How to link openssl statically](https://users.rust-lang.org/t/how-to-link-openssl-statically/14912/16) was a good read.

**Pull request merged**
